<?xml version="1.0"?>
<!-- adapted from stylesheet auto-generated by xmlstarlet sel -C -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:exslt="http://exslt.org/common" version="1.0" extension-element-prefixes="exslt">
  <xsl:output omit-xml-declaration="yes" indent="no" method="text"/>
  <xsl:template name="combo" match="/">
    <!-- output column names, separated by tabs -->
    <xsl:text>page_number&#9;height&#9;width&#9;top&#9;left&#9;position&#10;</xsl:text>
    <xsl:for-each select="//page">
      <xsl:value-of select="concat(@number,'&#9;',@height,'&#9;',@width,'&#9;',@top,'&#9;',@left,'&#9;', @position,'&#10;')"/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
